language: node_js
node_js:
  - "8"

branches:
  only:
    - develop

before_script:
  - npm install

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master