language: node_js
node_js:
  - "12"

branches:
  only:
    - develop

before_script:
  - npm install

script:
  npm run build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: develop